### ISSUE TITLE
老哥可否给个yolo_coco_initial.ckpt链接。多谢

### ISSUE THREAD

**Issue by wingerboy** [Stinky-Tofu/YOLO_V3#1]

**Comment by Stinky-Tofu** [comment]
> _No description provided._

https://drive.google.com/drive/my-drive

**Comment by hxy1051653358** [comment]
@Stinky-Tofu 这个链接打开没有权重文件呢？

**Comment by Stinky-Tofu** [comment]
> @Stinky-Tofu 这个链接打开没有权重文件呢？

有啊，你点进去看

**Comment by hxy1051653358** [comment]
@Stinky-Tofu 打开只是我自己的谷歌云盘 没有分享的权重文件

**Comment by xinyuegtxy** [comment]
你这个anchor size怎么设置的，不是应该用kmeans生成对应大小吗？你那个config怎么弄成那样

**Comment by Stinky-Tofu** [comment]
> @Stinky-Tofu 打开只是我自己的谷歌云盘 没有分享的权重文件



> 你这个anchor size怎么设置的，不是应该用kmeans生成对应大小吗？你那个config怎么弄成那样

**Comment by Stinky-Tofu** [comment]
我没有用kmeans重新生成anchor，用的论文里面的anchor，那些anchor都是已经除了stride的 @xinyuegtxy

**Comment by Stinky-Tofu** [comment]
我共享了啊 @hxy1051653358

**Comment by hxy1051653358** [comment]
@Stinky-Tofu  不好意思 我确实没有看到共享的文件  如果方便的话能发我邮箱一份吗？1051653358@qq.com 非常感谢

**Comment by Stinky-Tofu** [comment]
> @Stinky-Tofu 不好意思 我确实没有看到共享的文件 如果方便的话能发我邮箱一份吗？[1051653358@qq.com](mailto:1051653358@qq.com) 非常感谢

抱歉，文件太大了

**Comment by Stinky-Tofu** [comment]
https://drive.google.com/drive/folders/1We_P5L4nlLofR0IJJXzS7EEklZGUb9sz @hxy1051653358

**Comment by hxy1051653358** [comment]
@Stinky-Tofu 这个链接我看到了text权重，还是没有yolo_coco_initial.ckpt

**Comment by Stinky-Tofu** [comment]
yolo_coco_initial.ckpt还是好久之前的代码需要的文件了，现在按照readme来就可以获取voc_fine_tune.weights了 @hxy1051653358

**Comment by hxy1051653358** [comment]
@Stinky-Tofu 我想训练自己的数据集 还能用voc_fine_tune.weights吗？
在转换权重过程中出现问题Traceback (most recent call last):
  File "/home/hxy/Stronger-yolo/yolov3_to_tf/convert_weights.py", line 5, in <module>
    import yolo_v3
  File "/home/hxy/Stronger-yolo/yolov3_to_tf/yolo_v3.py", line 67
    def _fixed_padding(inputs, kernel_size, *args, mode='CONSTANT', **kwargs):
                                                      ^
SyntaxError: invalid syntax

**Comment by xinyuegtxy** [comment]
> 我没有用kmeans重新生成anchor，用的论文里面的anchor，那些anchor都是已经除了stride的 @xinyuegtxy

能改成keras yolo3那中anchor吗？你这个stride多大啊

**Comment by xinyuegtxy** [comment]
老哥，改成keras吧，tf写的太啰嗦了我感觉

**Comment by Stinky-Tofu** [comment]
> 老哥，改成keras吧，tf写的太啰嗦了我感觉

tf比较灵活，我比较喜欢tf，所以您要是想用keras的话，您可以把它改成keras版本的

**Comment by xinyuegtxy** [comment]
老哥，我懒啊，你赶紧写个吧，肯定很多star, tf不灵活啊，没有keras灵活啊

**Comment by Stinky-Tofu** [comment]
@xinyuegtxy 拒绝。。。keras修改内部层不方便，后期需要修改一些网络结构所以不想用keras

**Comment by jwnirvana** [comment]
> @Stinky-Tofu 我想训练自己的数据集 还能用voc_fine_tune.weights吗？
> 在转换权重过程中出现问题Traceback (most recent call last):
> File "/home/hxy/Stronger-yolo/yolov3_to_tf/convert_weights.py", line 5, in 
> import yolo_v3
> File "/home/hxy/Stronger-yolo/yolov3_to_tf/yolo_v3.py", line 67
> def _fixed_padding(inputs, kernel_size, *args, mode='CONSTANT', **kwargs):
> ^
> SyntaxError: invalid syntax

朋友，我和你一样的报错，请问你解决了吗？
