### ISSUE TITLE
亲测，项目没有问题！

### ISSUE THREAD

**Issue by fanbinqi** [Stinky-Tofu/YOLO_V3#16]

**Comment by Stinky-Tofu** [comment]
> 报错invalid literal for int() with base 10: 这个是什么原因呀？我用的也是python2

不是吧，我怕我readme写错了，所以就特意按readme跑了一遍，是发现有个bug（之前需要在log文件夹下新建一个train文件夹），但是已经解决这个bug，然后就没有发现其他bug了，完全按照raedme来跑的，可以得到完全相同的结果啊

**Comment by Stinky-Tofu** [comment]
> 报错invalid literal for int() with base 10: 这个是什么原因呀？我用的也是python2

你这个bug是哪个文件哪行的？

**Comment by fanbinqi** [comment]
Traceback (most recent call last):
  File "train.py", line 197, in <module>
    YoloTrain().train()
  File "train.py", line 127, in train
    in self.__train_data:
  File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 102, in next
    image, bboxes = self.__parse_annotation(annotation)
  File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 139, in __parse_annotation
    bboxes = np.array([map(int, box.split(',')) for box in line[1:]])
ValueError: invalid literal for int() with base 10: 'learning/stronger_yolo/YOLO_V3/data/VOC/2007_trainval/JPEGImages/007072.jpg'

**Comment by Stinky-Tofu** [comment]
> Traceback (most recent call last):
> File "train.py", line 197, in 
> YoloTrain().train()
> File "train.py", line 127, in train
> in self.__train_data:
> File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 102, in next
> image, bboxes = self.__parse_annotation(annotation)
> File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 139, in __parse_annotation
> bboxes = np.array([map(int, box.split(',')) for box in line[1:]])
> ValueError: invalid literal for int() with base 10: 'learning/stronger_yolo/YOLO_V3/data/VOC/2007_trainval/JPEGImages/007072.jpg'

你是python2.几的版本？

**Comment by Stinky-Tofu** [comment]
> > Traceback (most recent call last):
> > File "train.py", line 197, in
> > YoloTrain().train()
> > File "train.py", line 127, in train
> > in self.__train_data:
> > File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 102, in next
> > image, bboxes = self.__parse_annotation(annotation)
> > File "/home/zdh1901/deep_learning/stronger_yolo/YOLO_V3/data.py", line 139, in __parse_annotation
> > bboxes = np.array([map(int, box.split(',')) for box in line[1:]])
> > ValueError: invalid literal for int() with base 10: 'learning/stronger_yolo/YOLO_V3/data/VOC/2007_trainval/JPEGImages/007072.jpg'
> 
> 你是python2.几的版本？

微信联系我18890099926

**Comment by fanbinqi** [comment]
没问题！很棒的work！训练跑出来效果很惊艳！作者人也很棒！！！建议使用与readme上面相同的环境，python3问题有点多~~~

**Comment by wangg12** [comment]
@fanbinqi Could you explain what are the problems with python3?

**Comment by Stinky-Tofu** [comment]
@fanbinqi Maybe you need https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html

**Comment by fanbinqi** [comment]
@wangg12 个人建议你可以先用python2跑一下，后面根据报错改就好了

**Comment by zhaoxin111** [comment]
代码写的好好，今天想尝试一下来着，发现tf现在在windows不支持py2.7了。

**Comment by Stinky-Tofu** [comment]
@zhaoxin111 一直在服务器上跑的，不知道啊，后续应该会release python3版本的

**Comment by zhaoxin111** [comment]
@Stinky-Tofu 如果支持py3那就太好啦，谢谢分享

**Comment by noobgrow** [comment]
@fanbinqi  @Stinky-Tofu 你好想问一下这个测试的速度大概多少fps?

**Comment by zhuolyang** [comment]
@Stinky-Tofu 
你好，能否在README中添加ground truth格式说明？这样也许可以帮助其他人更快建立自己的数据集

**Comment by Stinky-Tofu** [comment]
@zhuolyang  你好，这两天我把backbone换成mobilenet后，就不打算更新了（弃坑tensorflow，转投pytorch），所以代码仅供参考。

**Comment by fanbinqi** [comment]
> @Stinky-Tofu
> 你好，能否在README中添加ground truth格式说明？这样也许可以帮助其他人更快建立自己的数据集

训练自己的数据集时，还是建立VOC格式的，一般自己的数据集中xml文件没有difficult，读xml的时候把这个判断取消了就好了。

**Comment by fanbinqi** [comment]
> @zhuolyang 你好，这两天我把backbone换成mobilenet后，就不打算更新了（弃坑tensorflow，转投pytorch），所以代码仅供参考。

大佬！模型训练出来985M~~~

**Comment by fanbinqi** [comment]
> @zhuolyang 你好，这两天我把backbone换成mobilenet后，就不打算更新了（弃坑tensorflow，转投pytorch），所以代码仅供参考。

建议用mobilenet-4_1,5_5,6_1，FSSD_mobilenet我是这么做的。

**Comment by Stinky-Tofu** [comment]
@fanbinqi，你是只改了backbone吗？head有改吗？mAP可以达到多少？

**Comment by fanbinqi** [comment]
> @fanbinqi，你是只改了backbone吗？head有改吗？mAP可以达到多少？

嗯嗯，based-SSD。head没用动，mAP涨了4个多点。

**Comment by lyqlola** [comment]
> 没问题！很棒的work！训练跑出来效果很惊艳！作者人也很棒！！！建议使用与readme上面相同的环境，python3问题有点多~~~

你好，请问你是在自己的数据集上训练的吗？能详细介绍一下训练方法么？以及最后在验证集上的precision和recall能达到多少？万分感谢！

**Comment by lyqlola** [comment]
> 没问题！很棒的work！训练跑出来效果很惊艳！作者人也很棒！！！建议使用与readme上面相同的环境，python3问题有点多~~~

你好，请问你自己的数据集有多少张图片？能详细介绍一下训练方法么(学习率、迭代次数，etc)？以及最后在验证集上的precision和recall能达到多少？万分感谢！
