### ISSUE TITLE
训练自己数据集loss为nan

### ISSUE THREAD

**Issue by hxy1051653358** [Stinky-Tofu/YOLO_V3#22]
你好，我使用自己数据集进行训练，大概1000多张图片，五个类别，改了config.py中类别及data path 使用voc预训练权重，出现梯度爆炸是什么原因？
Traceback (most recent call last):
  File "train.py", line 197, in <module>
    YoloTrain().train()
  File "train.py", line 143, in train
    raise ArithmeticError('The gradient is exploded')
ArithmeticError: The gradient is exploded

**Comment by Stinky-Tofu** [comment]
> 你好，我使用自己数据集进行训练，大概1000多张图片，五个类别，改了config.py中类别及data path 使用voc预训练权重，出现梯度爆炸是什么原因？
> Traceback (most recent call last):
> File "train.py", line 197, in 
> YoloTrain().train()
> File "train.py", line 143, in train
> raise ArithmeticError('The gradient is exploded')
> ArithmeticError: The gradient is exploded

目前估计不支持训练自己的数据集，因为我没在其他数据集上跑过，所以可能会存在bug

**Comment by hxy1051653358** [comment]
@Stinky-Tofu 那你是在所有bn位置都换成了group normalization吗？还是如何使用的group normalization?

**Comment by Stinky-Tofu** [comment]
> @Stinky-Tofu 那你是在所有bn位置都换成了group normalization吗？还是如何使用的group normalization?

用过，但是没效果，所以就没用加进去了，只是提供了GN的开源代码

**Comment by Stinky-Tofu** [comment]
> > @Stinky-Tofu 那你是在所有bn位置都换成了group normalization吗？还是如何使用的group normalization?
> 
> 用过，但是没效果，所以就没用加进去了，只是提供了GN的开源代码

你加我微信吧，有问题私聊

**Comment by wizholy** [comment]
我在自己数据集上跑过，可以用

**Comment by TianboChen** [comment]
@wizholy 请问下 在自己的数据集上跑 类别数量不一样 在加载预训练模型时无法加载 需要怎么修改

**Comment by nobody-cheng** [comment]
@wizholy 你好，请问你的数据集在v1版本跑过吗，我的相同数据集在v2版本能跑通，但在v1版本刚开始训练就会报出nan，梯度爆炸，无法训练

**Comment by HangyuQ** [comment]
wizholy，您好，方便加下微信交流下吗？hy1786591   ，现在在用自己数据集训练，谢谢！
