### ISSUE TITLE
self.__steps_per_period 错误， numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by tianyexing** [Stinky-Tofu/YOLO_V3#58]
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    Yolo_train().train()
  File "train.py", line 31, in __init__
    self.__steps_per_period = len(self.__train_data)  
TypeError: 'numpy.float64' object cannot be interpreted as an integer
有人知道这里怎么改吗？
我用的python3.6，别的问题基本改掉了，只剩下这个问题。

**Comment by lukaisheng1203** [comment]
这个是怎么改的啊

**Comment by zhangyufei1995** [comment]
兄弟 你解决了吗  我也是py3.6

**Comment by eleflea** [comment]
@airu924123 @zhangyufei1995 将data.py第83行改为`__next__`。
