### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by yinggo** [Stinky-Tofu/YOLO_V3#6]
您好，我昨天能跑成功代码，今天更新之后，报错了><，请帮忙看看是哪里的问题 
我检查了数据annotation，图片，储存路径，之前跑成功过，应该没啥问题的。。
报错如下：

> Traceback (most recent call last):
  File "train.py", line 202, in <module>
    YoloTrain().train()
  File "train.py", line 166, in train
    in self.__test_data:
  File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 102, in next
    image, bboxes = self.__parse_annotation(annotation)
  File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 136, in __parse_annotation
    image, bboxes = data_aug.random_horizontal_flip(np.copy(image), np.copy(bboxes))
  File "/home/ds1/Downloads/YOLO_V3-master/utils/data_aug.py", line 53, in random_horizontal_flip
    _, w_img, _ = img.shape
ValueError: need more than 0 values to unpack

**Comment by Stinky-Tofu** [comment]
你好，我本来只是为了自己看，所以readme写的不详细，没想到这么多人给星星，我今天就特意写了一下readme，防止你们用我的代码时出现细节问题，按readme上的做是没什么问题的，你这个应该是数据准备阶段有问题。

**Comment by Stinky-Tofu** [comment]
> 您好，我昨天能跑成功代码，今天更新之后，报错了><，请帮忙看看是哪里的问题
> 我检查了数据annotation，图片，储存路径，之前跑成功过，应该没啥问题的。。
> 报错如下：
> 
> > Traceback (most recent call last):
> > File "train.py", line 202, in 
> > YoloTrain().train()
> > File "train.py", line 166, in train
> > in self.__test_data:
> > File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 102, in next
> > image, bboxes = self.__parse_annotation(annotation)
> > File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 136, in __parse_annotation
> > image, bboxes = data_aug.random_horizontal_flip(np.copy(image), np.copy(bboxes))
> > File "/home/ds1/Downloads/YOLO_V3-master/utils/data_aug.py", line 53, in random_horizontal_flip
> > _, w_img, _ = img.shape
> > ValueError: need more than 0 values to unpack

你好，我本来只是为了自己看，所以readme写的不详细，没想到这么多人给星星，我今天就特意写了一下readme，防止你们用我的代码时出现细节问题，按readme上的做是没什么问题的，你这个应该是数据准备阶段有问题。

**Comment by Stinky-Tofu** [comment]
> 您好，我昨天能跑成功代码，今天更新之后，报错了><，请帮忙看看是哪里的问题
> 我检查了数据annotation，图片，储存路径，之前跑成功过，应该没啥问题的。。
> 报错如下：
> 
> > Traceback (most recent call last):
> > File "train.py", line 202, in 
> > YoloTrain().train()
> > File "train.py", line 166, in train
> > in self.__test_data:
> > File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 102, in next
> > image, bboxes = self.__parse_annotation(annotation)
> > File "/home/ds1/Downloads/YOLO_V3-master/data.py", line 136, in __parse_annotation
> > image, bboxes = data_aug.random_horizontal_flip(np.copy(image), np.copy(bboxes))
> > File "/home/ds1/Downloads/YOLO_V3-master/utils/data_aug.py", line 53, in random_horizontal_flip
> > _, w_img, _ = img.shape
> > ValueError: need more than 0 values to unpack

我今天把多尺度训练也加进去了，提高了0.5个点左右，你可以用这个代码，然后按照readme来做，应该是没问题的
